default: &default
  adapter: postgresql
  encoding: utf8
  #username: rails_admin
  #password: P@ssw0rd
  pool: 5
  timeout: 5000

development:
  <<: *default
  host: localhost
  database: rails_db

test:
  <<: *default
  host: localhost
  database: rails_db

production:
  <<: *default
  host: ec2-54-235-255-27.compute-1.amazonaws.com
  database: d1mcu5v1lou2dq
  username: ypurvoltmixdoi
  password: WYMsHmDFuszyoIH1fD58LV9dGj
