default: &default
  adapter: postgresql
  host: localhost
  encoding: utf8
  #username: rails_admin
  #password: P@ssw0rd
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: rails_db

test:
  <<: *default
  database: rails_db

production:
  <<: *default
  database: rails_db
  username: pos
  password: <%= ENV['POS_DATABASE_PASSWORD'] %>
