# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a885deb79e9cf1f5baa7086b6f7db62d98bdc5e54a90e575987994c53944bdb6421b2ebf8a9e3145f31290d3574cf717e39b2503a8213e51cec939cbbf598bf

test:
  secret_key_base: 6a445190d8fdc887e63006b0577e4abac535f75dc40a5513eb7166137bcab13650e2becac75d184fe2234b1ed5178a984f879aa81f64e35c08ff25370636c345

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
